version: "3.1"

services:
  db:
    image: mongo
    restart: always
    container_name: conections-db
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - connections:/mongo:/data/db

volumes:
  connections:
